### ISSUE TITLE
Serialization issue: No multiprocessing capabilities

### ISSUE THREAD

**Issue by GPaolo** [ehw-fit/py-paretoarchive#1]
Whenever I try to parallelise the execution of my code, I get the following error:
```
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in paretoarchive.PyBspTreeArchive2.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
I looked around and found out that is due to a missing reduce function to serialize the pareto tree object.

**Comment by mrazekv** [comment]
I am sorry but we did not test this library in a parallel run. The BSP structure does not support parallelism. However, the structure is (from our point of view for 10^9 components) very fast. Perhaps there is an opportunity to make separate frontiers for each thread and then, in the master, reduce them into one. 

If you know how to solve this issue, you are welcome to make a pull request 😃

**Comment by GPaolo** [comment]
I was not talking about the parallel processing of the paretofront. 
The issue I have emerges once I create a `PyBspTreeArchive` object and then try to send it to a pool of workers to work on different datasets for which I wanted to calculate a pareto front for each one of them.

A solution could be to create a different `PyBspTreeArchive` for each worker at the initialization of the pool, but that would require the definition of global variables and init functions adding quite a bit of code overhead. 

I am solving it by adding a `__reduce__` function in the `paretoarchive_gen.pyx` to help pickle serialize the object and it seems to work. I'll do a pool request shortly so you can see if it is worth adding it or not :) 

A small example of the code that creates problems is this:
```python
from paretoarchive import PyBspTreeArchive
import multiprocessing as mp
import numpy as np

if __name__ == "__main__":
  objectives = 2
  datasets = 3
  points = 10
  pareto = PyBspTreeArchive(objectives=objectives)

  def feed(data):
    pareto.clear()
    for d in data:
      pareto.process(d)
    print(pareto.points())

  main_pool = mp.Pool(processes=2)
  data = np.random.random((datasets, points, objectives))
  main_pool.map(feed, data)
```

**Comment by mrazekv** [comment]
Hi @GPaolo ,
thank you for submitting this pull request. I've tested it using a following code
```python
import sys
sys.path.extend(['build/lib.win32-2.7','build/lib.linux-x86_64-2.7'])
from paretoarchive import PyBspTreeArchive
import multiprocessing as mp
import numpy as np

if __name__ == "__main__":
  objectives = 2
  datasets = 3
  points = 10
  pareto = PyBspTreeArchive(objectives=objectives)

  def feed(data):
    pareto.clear()
    for d in data:
      pareto.process(d)
    print(pareto.points())

  main_pool = mp.Pool(processes=2)
  data = np.random.random((datasets, points, objectives))
  print("Multi thread parsing")
  main_pool.map(feed, data)

  print("Single thread parsing")
  # single-thread parsing
  for d in data:
    print(PyBspTreeArchive(objectives=objectives).filter(d))
```

and the code you proposed is working (parallel version gave me same results as single thread). Thank you!
